window.SEARCH_INDEX = [
  // Chapter 1 — Monolith
  { id: "problem",           chapter: "chapter-1-monolith.html",           chapterTitle: "Chapter 1: Monolith",          section: "The problem",                        terms: ["Django monolith", "PostgreSQL", "session auth", "ECS", "Docker", "containerisation", "diploma project", "S3", "static assets", "Aurora PostgreSQL"] },
  { id: "what-was-built",    chapter: "chapter-1-monolith.html",           chapterTitle: "Chapter 1: Monolith",          section: "What was built in this chapter",     terms: ["Django", "ECS service", "session auth", "monolith architecture", "deployment"] },
  { id: "constraint",        chapter: "chapter-1-monolith.html",           chapterTitle: "Chapter 1: Monolith",          section: "The constraint that shaped everything", terms: ["real codebase", "constraints", "greenfield", "legacy system", "technical debt"] },
  { id: "trade-offs",        chapter: "chapter-1-monolith.html",           chapterTitle: "Chapter 1: Monolith",          section: "Key trade-offs",                      terms: ["monolith kept running", "session auth", "API layer", "trade-offs", "deployment strategy"] },
  { id: "decision-record",   chapter: "chapter-1-monolith.html",           chapterTitle: "Chapter 1: Monolith",          section: "Decision record",                     terms: ["ADR", "architectural decision record"] },

  // Chapter 2 — Decomposition
  { id: "why-decompose",     chapter: "chapter-2-4-decomposition.html",    chapterTitle: "Chapter 2: Decomposition",     section: "The Scaling Challenge",               terms: ["decomposition", "microservices", "monolith", "scaling", "deployment coupling"] },
  { id: "strangler-fig",      chapter: "chapter-2-4-decomposition.html",    chapterTitle: "Chapter 2: Decomposition",     section: "Strangler Fig Pattern",                terms: ["Strangler Fig", "facade", "ALB", "incremental extraction", "API gateway", "zero downtime", "evolutionary"] },
  { id: "services",           chapter: "chapter-2-4-decomposition.html",   chapterTitle: "Chapter 2: Decomposition",     section: "Platform Services Identified",        terms: ["FastAPI", "Catalogue Service", "Cart Service", "Order Service", "Notification Service", "DynamoDB", "SNS/SQS", "event streaming", "event-driven"] },
  { id: "event-driven",       chapter: "chapter-2-4-decomposition.html",   chapterTitle: "Chapter 2: Decomposition",     section: "Event-Driven Reliability",             terms: ["Saga pattern", "SNS", "SQS", "event streaming", "compensating actions", "distributed transactions", "loose coupling", "Aurora"] },
  { id: "trade-offs",        chapter: "chapter-2-4-decomposition.html",   chapterTitle: "Chapter 2: Decomposition",     section: "Key trade-offs",                      terms: ["DynamoDB", "monolith still running", "deployment overhead", "notification delay", "SNS SQS delay"] },
  { id: "decision-record",   chapter: "chapter-2-4-decomposition.html",   chapterTitle: "Chapter 2: Decomposition",     section: "Decision record",                     terms: ["ADR", "Strangler Fig", "ADR-002"] },

  // Chapter 3 — Maturity
  { id: "problem",           chapter: "chapter-5-7-maturity.html",       chapterTitle: "Chapter 3: Maturity",          section: "The problem",                        terms: ["operability", "observability", "distributed system", "order state", "JWT", "stateless auth", "authentication"] },
  { id: "operations-console",chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "Operations console",                  terms: ["SSE", "Server-Sent Events", "real-time", "operations console", "FastAPI", "staff dashboard", "unidirectional"] },
  { id: "identity-service",  chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "Identity service",                    terms: ["JWT", "RS256", "HS256", "asymmetric signing", "public key", "private key", "identity service", "stateless auth", "token verification"] },
  { id: "cicd",              chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "CI/CD pipeline",                      terms: ["CodeBuild", "CI/CD", "buildspecs", "centralised buildspec", "S3", "GitHub webhook", "pipeline"] },
  { id: "integration-tests",chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "Integration tests",                    terms: ["integration tests", "end-to-end", "order placement", "real network conditions"] },
  { id: "trade-offs",        chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "Key trade-offs",                      terms: ["SSE vs WebSocket", "RS256 vs HS256", "centralised buildspec", "trade-offs"] },
  { id: "decision-record",   chapter: "chapter-5-7-maturity.html",        chapterTitle: "Chapter 3: Maturity",          section: "Decision record",                     terms: ["ADR", "RS256", "JWT", "ADR-003"] },

  // Chapter 4 — Mobile
  { id: "problem",           chapter: "chapter-9-mobile.html",             chapterTitle: "Chapter 4: Mobile",            section: "The problem",                        terms: ["React Native", "mobile", "mobile client", "Expo", "cross-platform", "API-first"] },
  { id: "zero-backend-changes",chapter: "chapter-9-mobile.html",         chapterTitle: "Chapter 4: Mobile",            section: "Zero backend changes",                terms: ["API-first", "zero backend changes", "RESTful", "JWT", "Stripe payment intent", "clean interfaces", "stateless"] },
  { id: "technology",        chapter: "chapter-9-mobile.html",             chapterTitle: "Chapter 4: Mobile",            section: "Technology decisions",                 terms: ["Expo", "managed workflow", "EAS Build", "SecureStore", "JWT", "iOS simulator build", "preview build", "React Native"] },
  { id: "cicd",              chapter: "chapter-9-mobile.html",             chapterTitle: "Chapter 4: Mobile",            section: "CI/CD pipeline",                      terms: ["CodeBuild", "EAS", "Expo", "CI job", "release job", "dev branch", "prod branch", "TypeScript", "Jest", "SSM Parameter Store"] },
  { id: "trade-offs",        chapter: "chapter-9-mobile.html",             chapterTitle: "Chapter 4: Mobile",            section: "Key trade-offs",                      terms: ["Expo managed", "bare React Native", "simulator build", "App Store", "polling vs WebSocket", "10-second polling", "trade-offs"] },
  { id: "decision-record",   chapter: "chapter-9-mobile.html",             chapterTitle: "Chapter 4: Mobile",            section: "Decision record",                     terms: ["ADR", "Expo managed workflow", "ADR-004"] },

  // Infrastructure
  { id: "platform-consistency",chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",              section: "Platform Consistency",              terms: ["platform engineering", "consistency", "force multiplier", "cognitive load", "delivery acceleration", "AI assistance"] },
  { id: "repo-pattern",        chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",              section: "The repo pattern",                    terms: ["two-repo pattern", "application code", "infrastructure code", "service-config", "CloudFormation", "ECS", "dev branch", "prod branch", "GitHub"] },
  { id: "shared-infrastructure",chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",           section: "Shared infrastructure",              terms: ["ecs-infrastructure", "vpc-infrastructure", "task-definition", "parameters", "buildspecs", "deployment-cli", "VPC", "subnets", "ECS cluster", "ALB", "Route 53", "SSM", "CloudFormation"] },
  { id: "cicd-pattern",        chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",              section: "CI/CD pipeline pattern",             terms: ["CodeBuild", "GitHub webhook", "CloudFormation", "buildspec", "ECR", "ECS", "rolling deployment", "centralised buildspec", "S3"] },
  { id: "environment-management",chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",          section: "One-command environment management", terms: ["Step Function", "environment orchestration", "spin-up", "spin-down", "espressorders-spinup-automation", "dependency order", "ECS cluster", "ALB", "Aurora", "internal developer portal"] },
  { id: "why-it-matters",     chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",              section: "Why this matters for production",    terms: ["platform engineering", "onboarding", "environment promotion", "audit", "version control", "portable"] },
  { id: "decision-record",   chapter: "infrastructure-automation.html", chapterTitle: "Infrastructure",              section: "Decision record",                     terms: ["ADR", "two-repo pattern", "ADR-010"] },
];